import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { CreditCard, CalendarClock, Plus, Loader2, Trash2, Pencil, Play, Pause } from 'lucide-react';
import { api, getErrorMessage } from '@/lib/api';
import { rupees, shortDate } from '@/lib/format';
import { StatCard } from '@/components/StatCard';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ExportButtons } from '@/components/ExportButtons';
import type { ExportColumn } from '@/lib/export';

type Plan = 'MONTHLY' | 'YEARLY';

interface SubscriptionCharge {
  id: string;
  date: string;
  plan: Plan;
  periodKey: string | null;
  amount: string;
  dueDate: string;
  auto: boolean;
  note: string | null;
}

interface PlanConfig {
  id: Plan;
  enabled: boolean;
  amount: string;
  chargeDay: number;
  chargeMonth: number | null;
  dueDays: number;
  startDate: string;
  generatedThrough: string | null;
}

const PLAN_LABEL: Record<Plan, string> = { MONTHLY: 'Monthly', YEARLY: 'Yearly' };

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

const CHARGE_COLUMNS: ExportColumn<SubscriptionCharge>[] = [
  { header: 'Charged On', value: (r) => shortDate(r.date) },
  { header: 'Plan', value: (r) => PLAN_LABEL[r.plan] },
  { header: 'Period', value: (r) => r.periodKey ?? 'One-off' },
  { header: 'Amount', value: (r) => rupees(r.amount), excel: (r) => Number(r.amount), numFmt: '#,##0.00', align: 'right' },
  { header: 'Due By', value: (r) => shortDate(r.dueDate) },
  { header: 'Source', value: (r) => (r.auto ? 'Auto' : 'Manual') },
  { header: 'Note', value: (r) => r.note ?? '' },
];

const today = () => new Date().toISOString().slice(0, 10);
const ordinal = (n: number) => {
  const s = ['th', 'st', 'nd', 'rd'];
  const v = n % 100;
  return `${n}${s[(v - 20) % 10] ?? s[v] ?? s[0]}`;
};

/** Whole days between two calendar dates, positive when `to` is later. */
function daysUntil(iso: string): number {
  const day = 24 * 60 * 60 * 1000;
  const at = (d: Date) => Date.UTC(d.getFullYear(), d.getMonth(), d.getDate());
  return Math.round((at(new Date(iso)) - at(new Date())) / day);
}

/**
 * Recurring subscription fees - the Expenses → Subscription tab.
 *
 * Charges are generated by the server (yearly on its renewal date, monthly on its
 * charge day); this page reads them, shows how the recurrence is set up, and
 * allows a one-off charge to be added by hand. Unrelated to `Subscription.tsx`,
 * which is the developer-only SaaS licensing gate for the deployment itself.
 */
export default function SubscriptionExpense() {
  const qc = useQueryClient();
  const [addOpen, setAddOpen] = useState(false);
  const [editing, setEditing] = useState<PlanConfig | null>(null);
  const [editingChargeId, setEditingChargeId] = useState<string | null>(null);
  const [form, setForm] = useState({ date: today(), plan: 'MONTHLY' as Plan, amount: '', dueDate: '', note: '' });

  const { data: rows = [], isLoading } = useQuery({
    queryKey: ['subscription-charges'],
    queryFn: () => api<SubscriptionCharge[]>('/subscription-charges'),
  });

  const { data: plans = [] } = useQuery({
    queryKey: ['subscription-plans'],
    queryFn: () => api<PlanConfig[]>('/subscription-plans'),
  });

  const invalidate = () => {
    qc.invalidateQueries({ queryKey: ['subscription-charges'] });
    qc.invalidateQueries({ queryKey: ['subscription-plans'] });
    qc.invalidateQueries({ queryKey: ['husk-pnl'] });
    qc.invalidateQueries({ queryKey: ['profit-loss'] });
    qc.invalidateQueries({ queryKey: ['payments'] });
    qc.invalidateQueries({ queryKey: ['accounts'] });
    qc.invalidateQueries({ queryKey: ['journal-entries'] });
  };

  const createMutation = useMutation({
    mutationFn: (body: any) => api('/subscription-charges', { method: 'POST', body }),
    onSuccess: () => {
      toast.success('Subscription charge recorded');
      invalidate();
      setAddOpen(false);
      setForm({ date: today(), plan: 'MONTHLY', amount: '', dueDate: '', note: '' });
    },
    onError: (e: Error) => toast.error(getErrorMessage(e)),
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, body }: { id: string; body: any }) => api(`/subscription-charges/${id}`, { method: 'PUT', body }),
    onSuccess: () => {
      toast.success('Subscription charge updated');
      invalidate();
      setAddOpen(false);
      setEditingChargeId(null);
      setForm({ date: today(), plan: 'MONTHLY', amount: '', dueDate: '', note: '' });
    },
    onError: (e: Error) => toast.error(getErrorMessage(e)),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => api(`/subscription-charges/${id}`, { method: 'DELETE' }),
    onSuccess: () => { toast.success('Charge deleted'); invalidate(); },
    onError: (e: Error) => toast.error(getErrorMessage(e)),
  });

  const planMutation = useMutation({
    mutationFn: ({ id, ...body }: { id: Plan } & Record<string, unknown>) =>
      api(`/subscription-plans/${id}`, { method: 'PATCH', body }),
    onSuccess: () => { toast.success('Plan updated'); invalidate(); setEditing(null); },
    onError: (e: Error) => toast.error(getErrorMessage(e)),
  });

  function submit() {
    const amount = parseFloat(form.amount);
    if (!form.date || !Number.isFinite(amount) || amount <= 0) {
      toast.error('Enter a valid date and amount');
      return;
    }
    const body = {
      date: form.date,
      plan: form.plan,
      amount,
      dueDate: form.dueDate || form.date,
      note: form.note || null,
    };
    if (editingChargeId) updateMutation.mutate({ id: editingChargeId, body });
    else createMutation.mutate(body);
  }

  function openEditCharge(r: SubscriptionCharge) {
    setEditingChargeId(r.id);
    setForm({ date: r.date.slice(0, 10), plan: r.plan, amount: String(Number(r.amount)), dueDate: r.dueDate.slice(0, 10), note: r.note ?? '' });
    setAddOpen(true);
  }

  function openAddCharge() {
    setEditingChargeId(null);
    setForm({ date: today(), plan: 'MONTHLY', amount: '', dueDate: '', note: '' });
    setAddOpen(true);
  }

  const total = rows.reduce((s, r) => s + Number(r.amount), 0);
  const yearlyTotal = rows.filter((r) => r.plan === 'YEARLY').reduce((s, r) => s + Number(r.amount), 0);
  const monthlyTotal = rows.filter((r) => r.plan === 'MONTHLY').reduce((s, r) => s + Number(r.amount), 0);

  const blurb = 'Recurring subscription fees. Each charge posts automatically on its renewal date, is deducted from the husk recovery pool and lands in the Profit & Loss as an operating expense.';

  const actions = (
    <>
      <ExportButtons filename="Subscription_Charges" title="Subscription Charges" subtitle={`${rows.length} charge(s)`} columns={CHARGE_COLUMNS} rows={rows} />
      <Button onClick={openAddCharge}><Plus className="h-4 w-4 mr-1.5" /> Add one-off</Button>
    </>
  );

  return (
    <div className="space-y-7">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <p className="text-sm text-muted-foreground max-w-2xl">{blurb}</p>
        <div className="flex items-center gap-2">{actions}</div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <StatCard label="Total subscription cost" value={rupees(total)} icon={CreditCard} tone="amber" hint="to husk pool & P&L" />
        <StatCard label="Yearly plan" value={rupees(yearlyTotal)} icon={CalendarClock} tone="gold" hint="all renewals" />
        <StatCard label="Monthly plan" value={rupees(monthlyTotal)} icon={CalendarClock} tone="forest" hint="all months" />
      </div>

      {/* ── Recurrence settings: one card per plan ── */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {plans.map((p) => (
          <div key={p.id} className="rounded-lg border bg-card p-4 space-y-3">
            <div className="flex items-start justify-between gap-3">
              <div>
                <div className="flex items-center gap-2">
                  <h3 className="font-display text-base font-semibold tracking-tight">{PLAN_LABEL[p.id]} subscription</h3>
                  <Badge variant={p.enabled ? 'success' : 'secondary'}>{p.enabled ? 'Active' : 'Paused'}</Badge>
                </div>
                <p className="text-sm text-muted-foreground mt-1">
                  {rupees(p.amount)} charged{' '}
                  {p.id === 'YEARLY'
                    ? `every ${ordinal(p.chargeDay)} ${MONTHS[(p.chargeMonth ?? 7) - 1]}`
                    : `on the ${ordinal(p.chargeDay)} of every month`}
                  {p.dueDays > 0 ? `, payable within ${p.dueDays} days` : ''}.
                </p>
                <p className="text-xs text-muted-foreground mt-1">
                  Charging since {shortDate(p.startDate)}
                  {p.generatedThrough ? ` · last posted ${shortDate(p.generatedThrough)}` : ' · nothing posted yet'}
                </p>
              </div>
              <div className="flex items-center gap-1 shrink-0">
                <Button
                  size="icon"
                  variant="ghost"
                  title={p.enabled ? 'Pause this plan' : 'Resume this plan'}
                  disabled={planMutation.isPending}
                  onClick={() => planMutation.mutate({ id: p.id, enabled: !p.enabled })}
                >
                  {p.enabled ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4 text-forest" />}
                </Button>
                <Button size="icon" variant="ghost" title="Edit recurrence" onClick={() => setEditing(p)}>
                  <Pencil className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="rounded-lg border bg-card overflow-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Charged On</TableHead>
              <TableHead>Plan</TableHead>
              <TableHead>Period</TableHead>
              <TableHead className="text-right">Amount</TableHead>
              <TableHead>Due By</TableHead>
              <TableHead>Source</TableHead>
              <TableHead>Note</TableHead>
              <TableHead className="text-center w-16">Action</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {isLoading ? (
              <TableRow><TableCell colSpan={8} className="text-center py-8"><Loader2 className="h-6 w-6 animate-spin text-primary inline" /></TableCell></TableRow>
            ) : rows.length === 0 ? (
              <TableRow><TableCell colSpan={8} className="text-center text-muted-foreground py-8">No subscription charges yet - the first one posts on its renewal date.</TableCell></TableRow>
            ) : rows.map((r) => {
              const left = daysUntil(r.dueDate);
              return (
                <TableRow key={r.id}>
                  <TableCell>{shortDate(r.date)}</TableCell>
                  <TableCell className="font-medium">{PLAN_LABEL[r.plan]}</TableCell>
                  <TableCell className="text-muted-foreground">{r.periodKey ?? 'One-off'}</TableCell>
                  <TableCell className="text-right font-mono tabular-nums">{rupees(r.amount)}</TableCell>
                  <TableCell>
                    <span className="mr-2">{shortDate(r.dueDate)}</span>
                    {left < 0 ? (
                      <Badge variant="destructive">{Math.abs(left)}d overdue</Badge>
                    ) : left <= 7 ? (
                      <Badge variant="warning">{left === 0 ? 'due today' : `${left}d left`}</Badge>
                    ) : null}
                  </TableCell>
                  <TableCell>
                    <Badge variant={r.auto ? 'soft' : 'outline'}>{r.auto ? 'Auto' : 'Manual'}</Badge>
                  </TableCell>
                  <TableCell className="text-muted-foreground">{r.note ?? '-'}</TableCell>
                  <TableCell className="text-center">
                    <div className="flex items-center justify-center gap-1">
                      <Button size="icon" variant="ghost" onClick={() => openEditCharge(r)}>
                        <Pencil className="h-4 w-4" />
                      </Button>
                      <Button size="icon" variant="ghost" onClick={() => deleteMutation.mutate(r.id)} disabled={deleteMutation.isPending}>
                        <Trash2 className="h-4 w-4 text-destructive" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      </div>

      {/* ── Add / edit a charge ── */}
      <Dialog open={addOpen} onOpenChange={(o) => { setAddOpen(o); if (!o) setEditingChargeId(null); }}>
        <DialogContent className="sm:max-w-sm">
          <DialogHeader><DialogTitle>{editingChargeId ? 'Edit' : 'Add'} Subscription Charge</DialogTitle></DialogHeader>
          <div className="space-y-4 py-2">
            <div className="space-y-1">
              <Label>Plan</Label>
              <Select value={form.plan} onValueChange={(v) => setForm((f) => ({ ...f, plan: v as Plan }))}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="MONTHLY">Monthly</SelectItem>
                  <SelectItem value="YEARLY">Yearly</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1">
              <Label>Charged on</Label>
              <Input type="date" value={form.date} onChange={(e) => setForm((f) => ({ ...f, date: e.target.value }))} />
            </div>
            <div className="space-y-1">
              <Label>Amount (₹)</Label>
              <Input type="number" step="0.01" value={form.amount} onChange={(e) => setForm((f) => ({ ...f, amount: e.target.value }))} placeholder="e.g. 2006" />
            </div>
            <div className="space-y-1">
              <Label>Due by (optional)</Label>
              <Input type="date" value={form.dueDate} onChange={(e) => setForm((f) => ({ ...f, dueDate: e.target.value }))} />
            </div>
            <div className="space-y-1">
              <Label>Note (optional)</Label>
              <Input value={form.note} onChange={(e) => setForm((f) => ({ ...f, note: e.target.value }))} />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setAddOpen(false)}>Cancel</Button>
            <Button onClick={submit} disabled={createMutation.isPending || updateMutation.isPending}>
              {(createMutation.isPending || updateMutation.isPending) ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Save'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <PlanDialog
        plan={editing}
        onClose={() => setEditing(null)}
        onSave={(body) => editing && planMutation.mutate({ id: editing.id, ...body })}
        saving={planMutation.isPending}
      />
    </div>
  );
}

/** Edit one plan's recurrence: amount, when it charges, and the payment window. */
function PlanDialog({
  plan,
  onClose,
  onSave,
  saving,
}: {
  plan: PlanConfig | null;
  onClose: () => void;
  onSave: (body: Record<string, unknown>) => void;
  saving: boolean;
}) {
  const [form, setForm] = useState({ amount: '', chargeDay: '', chargeMonth: '7', dueDays: '', startDate: '' });

  // Re-seed the form whenever a different plan is opened.
  const [seededFor, setSeededFor] = useState<Plan | null>(null);
  if (plan && seededFor !== plan.id) {
    setSeededFor(plan.id);
    setForm({
      amount: String(Number(plan.amount)),
      chargeDay: String(plan.chargeDay),
      chargeMonth: String(plan.chargeMonth ?? 7),
      dueDays: String(plan.dueDays),
      startDate: plan.startDate.slice(0, 10),
    });
  }

  function save() {
    const amount = parseFloat(form.amount);
    const chargeDay = parseInt(form.chargeDay, 10);
    if (!Number.isFinite(amount) || amount <= 0) return toast.error('Enter a valid amount');
    if (!Number.isInteger(chargeDay) || chargeDay < 1 || chargeDay > 31) return toast.error('Charge day must be 1-31');
    onSave({
      amount,
      chargeDay,
      chargeMonth: plan?.id === 'YEARLY' ? parseInt(form.chargeMonth, 10) : null,
      dueDays: parseInt(form.dueDays || '0', 10),
      startDate: form.startDate,
    });
  }

  return (
    <Dialog open={!!plan} onOpenChange={(o) => { if (!o) { setSeededFor(null); onClose(); } }}>
      <DialogContent className="sm:max-w-sm">
        <DialogHeader><DialogTitle>{plan ? PLAN_LABEL[plan.id] : ''} Subscription Settings</DialogTitle></DialogHeader>
        <div className="space-y-4 py-2">
          <div className="space-y-1">
            <Label>Fee (₹)</Label>
            <Input type="number" step="0.01" value={form.amount} onChange={(e) => setForm((f) => ({ ...f, amount: e.target.value }))} />
          </div>
          {plan?.id === 'YEARLY' && (
            <div className="space-y-1">
              <Label>Renewal month</Label>
              <Select value={form.chargeMonth} onValueChange={(v) => setForm((f) => ({ ...f, chargeMonth: v }))}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {MONTHS.map((m, i) => <SelectItem key={m} value={String(i + 1)}>{m}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
          )}
          <div className="space-y-1">
            <Label>Charge day of month</Label>
            <Input type="number" min="1" max="31" value={form.chargeDay} onChange={(e) => setForm((f) => ({ ...f, chargeDay: e.target.value }))} />
            <p className="text-xs text-muted-foreground">A day past the end of a short month falls back to its last day.</p>
          </div>
          <div className="space-y-1">
            <Label>Payment window (days)</Label>
            <Input type="number" min="0" value={form.dueDays} onChange={(e) => setForm((f) => ({ ...f, dueDays: e.target.value }))} />
          </div>
          <div className="space-y-1">
            <Label>Charge from</Label>
            <Input type="date" value={form.startDate} onChange={(e) => setForm((f) => ({ ...f, startDate: e.target.value }))} />
            <p className="text-xs text-muted-foreground">Moving this earlier does not create past charges - already-posted periods are never re-generated.</p>
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => { setSeededFor(null); onClose(); }}>Cancel</Button>
          <Button onClick={save} disabled={saving}>{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Save'}</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
