-- Migration for Resend Email Delivery & Tracking
ALTER TYPE "EmailStatus" ADD VALUE IF NOT EXISTS 'DELIVERED';
ALTER TYPE "EmailStatus" ADD VALUE IF NOT EXISTS 'OPENED';
ALTER TYPE "EmailStatus" ADD VALUE IF NOT EXISTS 'CLICKED';
ALTER TYPE "EmailStatus" ADD VALUE IF NOT EXISTS 'BOUNCED';
ALTER TYPE "EmailStatus" ADD VALUE IF NOT EXISTS 'COMPLAINED';

ALTER TABLE "EmailLog" ADD COLUMN IF NOT EXISTS "deliveredAt" TIMESTAMP(3);
ALTER TABLE "EmailLog" ADD COLUMN IF NOT EXISTS "openedAt" TIMESTAMP(3);
ALTER TABLE "EmailLog" ADD COLUMN IF NOT EXISTS "clickedAt" TIMESTAMP(3);
ALTER TABLE "EmailLog" ADD COLUMN IF NOT EXISTS "bouncedAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "EmailLog_resendMessageId_idx" ON "EmailLog"("resendMessageId");
