import type { ShortcutDefinition } from './types';

export const DEFAULT_SHORTCUTS: ShortcutDefinition[] = [
  // ── Global Actions ──────────────────────────────────────────────────────────
  {
    id: 'action:command-palette',
    label: 'Command Palette / Quick Search',
    description: 'Open the spotlight command palette to search pages, parties, orders, and trigger quick actions',
    category: 'actions',
    keys: ['Ctrl', 'k'],
    defaultKeys: ['Ctrl', 'k'],
    actionType: 'command-palette',
    isEnabled: true,
    globalInInputs: true,
  },
  {
    id: 'action:cheat-sheet',
    label: 'Keyboard Shortcuts Help',
    description: 'Open the visual cheat sheet modal displaying all shortcuts',
    category: 'actions',
    keys: ['?'],
    defaultKeys: ['?'],
    actionType: 'cheat-sheet',
    isEnabled: true,
    globalInInputs: false,
  },
  {
    id: 'action:theme-toggle',
    label: 'Toggle Dark / Light Theme',
    description: 'Switch between dark and light appearance modes',
    category: 'actions',
    keys: ['Alt', 't'],
    defaultKeys: ['Alt', 't'],
    actionType: 'toggle-theme',
    isEnabled: true,
    globalInInputs: true,
  },
  {
    id: 'action:sidebar-toggle',
    label: 'Toggle Sidebar',
    description: 'Collapse or expand the left navigation sidebar',
    category: 'actions',
    keys: ['Alt', 'b'],
    defaultKeys: ['Alt', 'b'],
    actionType: 'toggle-sidebar',
    isEnabled: true,
    globalInInputs: true,
  },
  {
    id: 'action:focus-search',
    label: 'Focus Page Search Filter',
    description: 'Focus the primary search or filter input on the current page',
    category: 'actions',
    keys: ['/'],
    defaultKeys: ['/'],
    actionType: 'focus-search',
    isEnabled: true,
    globalInInputs: false,
  },
  {
    id: 'action:quick-new',
    label: 'Quick New Record',
    description: 'Trigger the create / new record button or modal on the active page',
    category: 'actions',
    keys: ['Alt', 'n'],
    defaultKeys: ['Alt', 'n'],
    actionType: 'quick-new',
    isEnabled: true,
    globalInInputs: true,
  },
  {
    id: 'action:refresh',
    label: 'Refresh Page Data',
    description: 'Re-fetch queries and update current view data without full browser reload',
    category: 'actions',
    keys: ['Alt', 'r'],
    defaultKeys: ['Alt', 'r'],
    actionType: 'refresh',
    isEnabled: true,
    globalInInputs: true,
  },
  {
    id: 'action:escape',
    label: 'Close Active Modal / Clear',
    description: 'Dismiss any open dialog, modal, drawer, or search dropdown',
    category: 'actions',
    keys: ['Escape'],
    defaultKeys: ['Escape'],
    actionType: 'command-palette', // Handled specially
    isEnabled: true,
    globalInInputs: true,
  },

  // ── Navigation: Core & Master Data ──────────────────────────────────────────
  {
    id: 'nav:home',
    label: 'Go to Home',
    description: 'Navigate to the main landing overview',
    category: 'navigation',
    keys: ['g', 'h'],
    defaultKeys: ['g', 'h'],
    targetUrl: '/',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:dashboard',
    label: 'Go to Dashboard',
    description: 'Navigate to business analytics and KPIs dashboard',
    category: 'navigation',
    keys: ['g', 'd'],
    defaultKeys: ['g', 'd'],
    targetUrl: '/dashboard',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:parties',
    label: 'Go to Parties',
    description: 'Manage suppliers, buyers, and hamali teams',
    category: 'navigation',
    keys: ['g', 'p'],
    defaultKeys: ['g', 'p'],
    targetUrl: '/parties',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:brokers',
    label: 'Go to Brokers',
    description: 'Manage registered brokers and commission rates',
    category: 'navigation',
    keys: ['g', 'b'],
    defaultKeys: ['g', 'b'],
    targetUrl: '/brokers',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:transports',
    label: 'Go to Transports',
    description: 'Manage transporters, lorry fleets, and destinations',
    category: 'navigation',
    keys: ['g', 't'],
    defaultKeys: ['g', 't'],
    targetUrl: '/transports',
    actionType: 'navigate',
    isEnabled: true,
  },

  // ── Purchases & Stock ───────────────────────────────────────────────────────
  {
    id: 'nav:purchase-orders',
    label: 'Go to Purchase Orders',
    description: 'View and create supplier purchase orders',
    category: 'purchases',
    keys: ['g', 'o'],
    defaultKeys: ['g', 'o'],
    targetUrl: '/purchase-orders',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:stock-in',
    label: 'Go to Stock In',
    description: 'Record incoming lorry arrivals and weighbridge entries',
    category: 'purchases',
    keys: ['g', 'i'],
    defaultKeys: ['g', 'i'],
    targetUrl: '/stock-in',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:purchases',
    label: 'Go to Stock in Detail',
    description: 'Purchases register, detailed weights, and quality cuts',
    category: 'purchases',
    keys: ['g', 'u'],
    defaultKeys: ['g', 'u'],
    targetUrl: '/purchases',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:verification',
    label: 'Go to Verification',
    description: 'Auditor invoice and weighbridge bill verification',
    category: 'purchases',
    keys: ['g', 'v'],
    defaultKeys: ['g', 'v'],
    targetUrl: '/verification',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:stock-overview',
    label: 'Go to Black Seed Stock',
    description: 'Unified warehouse stock overview across all locations',
    category: 'purchases',
    keys: ['g', 's'],
    defaultKeys: ['g', 's'],
    targetUrl: '/stock/overview',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:order-planner',
    label: 'Go to Order Planner',
    description: 'Stock by price bands, yield estimation, and dispatch planning',
    category: 'purchases',
    keys: ['g', 'r'],
    defaultKeys: ['g', 'r'],
    targetUrl: '/stock/price',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:stock-location',
    label: 'Go to Stock by Location',
    description: 'Physical location breakdown with band-level pricing',
    category: 'purchases',
    keys: ['g', 'l'],
    defaultKeys: ['g', 'l'],
    targetUrl: '/stock/location',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:stock-transfer',
    label: 'Go to Stock Transfer',
    description: 'Internal warehouse-to-warehouse stock transfers',
    category: 'purchases',
    keys: ['g', 'x'],
    defaultKeys: ['g', 'x'],
    targetUrl: '/stock/transfer',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:stock-date',
    label: 'Go to Stock by Date (FIFO)',
    description: 'First-in First-out aging analysis of raw material inventory',
    category: 'purchases',
    keys: ['g', 'f'],
    defaultKeys: ['g', 'f'],
    targetUrl: '/stock/date',
    actionType: 'navigate',
    isEnabled: true,
  },

  // ── Sales & Dispatches ──────────────────────────────────────────────────────
  {
    id: 'nav:sale-orders',
    label: 'Go to Sale Orders',
    description: 'Manage customer contracts, sale allocations, and statuses',
    category: 'sales',
    keys: ['g', 'e'],
    defaultKeys: ['g', 'e'],
    targetUrl: '/sale-orders',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:sales-pappu',
    label: 'Go to Pappu Sales',
    description: 'Pappu dispatches, tax invoices, E-Way bills, and lorry receipts',
    category: 'sales',
    keys: ['g', '1'],
    defaultKeys: ['g', '1'],
    targetUrl: '/sales/pappu',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:sales-husk',
    label: 'Go to Husk Sales',
    description: 'Husk dispatch billing and driver trip logs',
    category: 'sales',
    keys: ['g', '2'],
    defaultKeys: ['g', '2'],
    targetUrl: '/sales/husk',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:sales-tps',
    label: 'Go to TPS (Brokens)',
    description: 'Tamarind kernel broken seeds (TPS) sales register',
    category: 'sales',
    keys: ['g', '3'],
    defaultKeys: ['g', '3'],
    targetUrl: '/sales/tps',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:sales-byproducts',
    label: 'Go to Byproduct Sales',
    description: 'Tamarind shell, waste, and pre-cleaner byproduct dispatches',
    category: 'sales',
    keys: ['g', '4'],
    defaultKeys: ['g', '4'],
    targetUrl: '/sales/byproducts',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:sales-notes',
    label: 'Go to Credit / Debit Notes',
    description: 'Rate adjustments, quality deductions, and return credit notes',
    category: 'sales',
    keys: ['g', 'n'],
    defaultKeys: ['g', 'n'],
    targetUrl: '/sales/notes',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:sales-dues-today',
    label: 'Go to Dues on This Day',
    description: 'Daily cash collections timeline and overdue sales tracker',
    category: 'sales',
    keys: ['g', 'y'],
    defaultKeys: ['g', 'y'],
    targetUrl: '/sales/dues-today',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:pappu-profit-loss',
    label: 'Go to Pappu Profit & Loss',
    description: 'Real-time lot margin calculation and profitability report',
    category: 'sales',
    keys: ['g', 'w'],
    defaultKeys: ['g', 'w'],
    targetUrl: '/sales/profit-loss',
    actionType: 'navigate',
    isEnabled: true,
  },

  // ── Accounts & Ledgers ──────────────────────────────────────────────────────
  {
    id: 'nav:party-ledger',
    label: 'Go to Party Ledger',
    description: 'Statement of accounts for buyers, suppliers, and transports',
    category: 'accounts',
    keys: ['g', 'a'],
    defaultKeys: ['g', 'a'],
    targetUrl: '/accounts/party-ledger',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:hamali-ledger',
    label: 'Go to Hamali Report',
    description: 'Hamali crew loading/unloading rates and payment advances',
    category: 'accounts',
    keys: ['g', 'm'],
    defaultKeys: ['g', 'm'],
    targetUrl: '/accounts/hamali-ledger',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:brokerage-ledger',
    label: 'Go to Brokerage Report',
    description: 'Broker commissions accrued, paid, and outstanding balances',
    category: 'accounts',
    keys: ['g', 'k'],
    defaultKeys: ['g', 'k'],
    targetUrl: '/accounts/brokerage-ledger',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:journal-entries',
    label: 'Go to General Journal',
    description: 'Double-entry accounting journal vouchers',
    category: 'accounts',
    keys: ['g', 'j'],
    defaultKeys: ['g', 'j'],
    targetUrl: '/accounts/journal-entries',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:chart-of-accounts',
    label: 'Go to Chart of Accounts',
    description: 'General ledgers, assets, liabilities, and equity structure',
    category: 'accounts',
    keys: ['g', 'c'],
    defaultKeys: ['g', 'c'],
    targetUrl: '/accounts/chart-of-accounts',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:balance-sheet',
    label: 'Go to Balance Sheet',
    description: 'Financial position summary and trial balance',
    category: 'accounts',
    keys: ['g', 'z'],
    defaultKeys: ['g', 'z'],
    targetUrl: '/accounts/balance-sheet',
    actionType: 'navigate',
    isEnabled: true,
  },

  // ── Transactions & Reports ──────────────────────────────────────────────────
  {
    id: 'nav:payments',
    label: 'Go to Payments',
    description: 'Outward bank and cash payment vouchers',
    category: 'reports',
    keys: ['Alt', '1'],
    defaultKeys: ['Alt', '1'],
    targetUrl: '/transactions/payments',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:receipts',
    label: 'Go to Receipts',
    description: 'Inward payments collected from buyers',
    category: 'reports',
    keys: ['Alt', '2'],
    defaultKeys: ['Alt', '2'],
    targetUrl: '/transactions/receipts',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:sale-dues',
    label: 'Go to Sale Dues Report',
    description: 'Accounts receivable aging and outstanding buyer balances',
    category: 'reports',
    keys: ['Alt', '3'],
    defaultKeys: ['Alt', '3'],
    targetUrl: '/reports/sale-dues',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:purchase-dues',
    label: 'Go to Purchase Dues Report',
    description: 'Accounts payable to seed suppliers and prompt payment discounts',
    category: 'reports',
    keys: ['Alt', '4'],
    defaultKeys: ['Alt', '4'],
    targetUrl: '/reports/purchase-dues',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:payment-planner',
    label: 'Go to Payment Planner',
    description: 'Upcoming supplier cash flow forecasting and payment schedule',
    category: 'reports',
    keys: ['Alt', '5'],
    defaultKeys: ['Alt', '5'],
    targetUrl: '/reports/payment-planner',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:freight-dues',
    label: 'Go to Freight Dues',
    description: 'Lorry driver freight charges, advances, and dues ledger',
    category: 'reports',
    keys: ['Alt', '6'],
    defaultKeys: ['Alt', '6'],
    targetUrl: '/reports/freight-dues',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:taxes',
    label: 'Go to Taxes / GST',
    description: 'GST summaries, GSTR-1, GSTR-3B matching, and TDS reports',
    category: 'reports',
    keys: ['Alt', '7'],
    defaultKeys: ['Alt', '7'],
    targetUrl: '/reports/taxes',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:expenses',
    label: 'Go to Income & Expenses',
    description: 'Operating expenses, utility bills, and factory maintenance',
    category: 'reports',
    keys: ['Alt', '8'],
    defaultKeys: ['Alt', '8'],
    targetUrl: '/reports/expenses',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:storage-loans',
    label: 'Go to Storage Loans',
    description: 'Bank pledge loans on cold storage warehouse stock',
    category: 'reports',
    keys: ['Alt', '9'],
    defaultKeys: ['Alt', '9'],
    targetUrl: '/loans',
    actionType: 'navigate',
    isEnabled: true,
  },

  // ── Settings & System ───────────────────────────────────────────────────────
  {
    id: 'nav:settings',
    label: 'Go to Settings',
    description: 'Company profile, invoice layouts, freight rates, and configurations',
    category: 'actions',
    keys: ['Alt', 's'],
    defaultKeys: ['Alt', 's'],
    targetUrl: '/settings',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:settings-shortcuts',
    label: 'Go to Keyboard Shortcuts Settings',
    description: 'Open the shortcut customizer and key remapping screen',
    category: 'actions',
    keys: ['Alt', 'k'],
    defaultKeys: ['Alt', 'k'],
    targetUrl: '/settings?tab=shortcuts',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:notes',
    label: 'Go to Notes & Comments',
    description: 'Internal reminders, party comments, and operational memos',
    category: 'actions',
    keys: ['Alt', 'm'],
    defaultKeys: ['Alt', 'm'],
    targetUrl: '/notes-comments',
    actionType: 'navigate',
    isEnabled: true,
  },
  {
    id: 'nav:support',
    label: 'Go to Support Tickets',
    description: 'ERP issues, bug tracker, and help requests',
    category: 'actions',
    keys: ['Alt', 'q'],
    defaultKeys: ['Alt', 'q'],
    targetUrl: '/support',
    actionType: 'navigate',
    isEnabled: true,
  },
];
